### ISSUE TITLE
Empty Value for Fuji Xtrans raw data

### ISSUE THREAD

**Issue by cchen156** [neothemachine/rawpy-notebooks#2]
Hi I have used rawpy for a while. I found there is some problem when the Fuji raw data (.RAF)

When I use rawpy to read Sony raw files, everything seems right: I can load the black_level, raw_pattern, etc. However, all these values are almost zeros when I load a Fuji raw file with the format RAF. 

The raw_pattern is like:
[ 1 2 1 1 2 1]
[ 0 0 0 0 0 0 ]
...
[ 0 0 0 0 0 0]
And the black_level are also all zeros. 

Can anyone fix this problem?

**Comment by letmaik** [comment]
Hi there, thanks for posting. Can you please re-post in the https://github.com/letmaik/rawpy repository? The one here is rawpy-notebooks and is only concerned with issues of the ipython notebooks, not the library itself. Thanks! Also, when you post the issue it is immensly helpful to attach a sample image.
